### PR TITLE
fix: add ownerReferences to resources created by arena

### LINKED ISSUE #1339: Add ownerReferences to resources created by arena
### What you would like to be added?

When one uses Arena to submit a training job with `ttlSecondsAfterFinished` set, the training job will be cleaned up when the TTL is reached, but the associated resources created by Arena will not.

### Why is this needed?

Also clean up the resources created by Arena once the training job is deleted. Otherwise, there will be a large amount of resources (e.g. ConfigMaps) may remain uncleaned, leading to the resource leaks in the cluster.

### Love this feature?

Give it a 👍 We prioritize the features with most 👍

### PR DESCRIPTION
**Pull request by FAUST-BENCHOU**
## Purpose of this PR
Close https://github.com/kubeflow/arena/issues/1339

**Proposed changes:**

Call PatchOwnerReferenceWithAppInfoFile to add an ownerReference to all resources, pointing to the training job's CRD.

## Change Category

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that could affect existing functionality)
- [ ] Documentation update

### CODE REVIEW

File: pkg/util/kubectl/kubectl.go [hunk 1]
```diff
@@ -385,7 +386,36 @@ func UpdateLWSJob(lwsJob *lwsv1.LeaderWorkerSet) error {
...
+	case string(types.VolcanoTrainingJob):
+		return "jobs.batch.volcano.sh"
+	case string(types.SparkTrainingJob):
+		return "sparkapplications.sparkoperator.k8s.io"
+	case string(types.RayJob):
+		return "rayjobs.ray.io"
+	default:
+		return ""
+	}
+}
```
Comment (ChenYi015) [inline pkg/util/kubectl/kubectl.go:410]: Since the resource name does not have suffix `s` (e.g. `pytorchjob.kubeflow.org/pytorch-mnist`), we need to remove it to avoid patching ownerReference to training job itself.

```suggestion
func getTrainingJobCRDName(trainingType string) string {
	switch trainingType {
	case string(types.TFTrainingJob):
		return "tfjob.kubeflow.org"
	case string(types.PytorchTrainingJob):
		return "pytorchjob.kubeflow.org"
	case string(types.MPITrainingJob), string(types.HorovodTrainingJob):
		return "mpijob.kubeflow.org"
	case string(types.ETTrainingJob), string(types.DeepSpeedTrainingJob):
		return "trainingjob.kai.alibabacloud.com"
	case string(types.VolcanoTrainingJob):
		return "job.batch.volcano.sh"
	case string(types.SparkTrainingJob):
		return "sparkapplication.sparkoperator.k8s.io"
	case string(types.RayJob):
		return "rayjob.ray.io"
	default:
		return ""
	}
}
```

**Review by ChenYi015 — CHANGES_REQUESTED** [review]
@FAUST-BENCHOU Thanks for your contribution! Overall LGTM, one minor change needs to be made.

**Comment by FAUST-BENCHOU** [comment]
@ChenYi015 Done.Thanks for your review!

**Review by ChenYi015 — APPROVED** [review]
/approve
